name: Deploy Frontend and Backend

on:
  push:
    branches:
      - main

jobs:
  backend-deploy:
    name: Deploy Backend to DigitalOcean Droplet
    runs-on: ubuntu-latest

    steps:
      - name: SSH & Deploy Backend
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /home/root/aichatapp/backend
            git pull origin main
            npm install
            pm2 restart all

  frontend-deploy:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    needs: backend-deploy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Frontend to Vercel
        working-directory: frontend
        run: |
          npm install -g vercel
          npm install
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
